gText_HowMayIServeYou::
	.string "Welcome!\p"
	.string "How may I serve you?$"

gText_PleaseComeAgain::
	.string "Please come again!$"

gText_OpenCustomStore::
	.string "This is a store for custom items!$"

gText_ShopCustomStore::
	.string "This is the modded store!$"

gText_CustomStoreMegas::
    .string "Megas$"
gText_CustomStoreMints::
    .string "Mints$"
gText_CustomStoreEvolution::
    .string "Evolution$"
gText_CustomStoreBattle::
    .string "Battle$"

gText_PlayerWhatCanIDoForYou::
	.string "{PLAYER}{STRING 5}, welcome!\p"
	.string "What can I do for you?$"


